### ISSUE TITLE
GradCam maps

### ISSUE THREAD

**Issue by AmeenAli** [med-air/Contrastive-COVIDNet#2]
Hi,
first of all, thanks for sharing your awesome work!!!
any chances sharing the code for extracting GradCam maps?
Thanks
Best

**Comment by Kyfafyd** [comment]
Thanks for interesting in our work.
Well, there are a lot of references in github, here is an example: https://github.com/jacobgil/pytorch-grad-cam
You just need to modify the model building and loading your trained weights in code.
Hope helpful to you!

**Comment by AmeenAli** [comment]
@Kyfafyd 
Thanks for your reply,
a side question - what should the target layer be?
Thanks

**Comment by Kyfafyd** [comment]
For a common view, the target layer should be the `last layer` of the `feature extractor` in a CNN model.
i.e. the last convolutional layer before `global average pooling` or `fully connected` layer.

**Comment by AmeenAli** [comment]
Hi,
Thanks for the clarifying, However I am keeping getting some errors.
I am not sure how should in which sense I should change the model building. can you clarify? if you can upload code that's would be awesome. Thanks!

**Comment by Kyfafyd** [comment]
You should build a model and load the model needed weights. Sorry I do not have code for cam at hand.
If possible, can you show me your error and I will help you with it.

**Comment by AmeenAli** [comment]
Hi,
I want to extract the cam-maps after training is done, below is the code : 
`def get_gradcam_tensors(model , loader):
    with torch.no_grad():

     model.eval()
     grad_cam = GradCam(model=model, feature_module=model.pexp4_3, \
                       target_layer_names=["pexp4_3"], use_cuda=True)

     for idx , input_tensors in tqdm(enumerate(loader)):
         input_data, target, site  = input_tensors
         input_data = input_data.cuda()
         target = target.cuda()
         grayscale_cam = grad_cam(input_data.squeeze(), target)
`

However I get the following error : **RuntimeError: running_mean should contain 2048 elements not 64**
I don't load the weights because I use the model immediately after training is done.

**Comment by Kyfafyd** [comment]
As you get error `RuntimeError: running_mean should contain 2048 elements not 64`, it means your built model with batchnorm layer inputs dimension 2048, but from weights 64.
This is caused by wrongly building model

**Comment by AmeenAli** [comment]
Solved, Many thanks!
