### ISSUE TITLE
[BUG ?]

### ISSUE THREAD

**Issue by AmeenAli** [med-air/Contrastive-COVIDNet#3]
Hi,
I  have noticed that in dataset loader,
https://github.com/med-air/Contrastive-COVIDNet/blob/master/code/dataset.py#L33
you keep extending the original paths list with the same previous list, is this intended?
Also I don't see anyplace where you use newtrainlabel except in test, why you don't train on the 'new data' as well?
Thanks

**Comment by Kyfafyd** [comment]
Dear Ali,

As two datasets used for jointly training are not balanced, so we load the smaller dataset (COVID-CT) for four times.

Best, 
Zhao
