### ISSUE TITLE
validation or test 

### ISSUE THREAD

**Issue by ghost** [med-air/Contrastive-COVIDNet#4]
thanks for sharing your great work! 

Regarding the results in the paper, I have some questions. From the open source code, you seem to get the accuracy rate on test set at the end of each epoch.

So in the paper, is the epoch with the highest test metrics selected as the final result? or you use another validation set ?

thank you very much

**Comment by Kyfafyd** [comment]
Dear @moonlightarc

Thanks for your interests!
We use the test set to select model, and do not have other validation datasets.

Best, Zhao

**Comment by AI678** [comment]
thanks
