### ISSUE TITLE
paired t-test

### ISSUE THREAD

**Issue by nlpLover123** [med-air/Contrastive-COVIDNet#5]
Hi, thanks for sharing your code. I have one question about the p-value reported in your paper. How was it calculated ? Was it based on AUC or accuracy ?

**Comment by Kyfafyd** [comment]
Thanks very much for your interest!
It is based on the network prediction, for calculation, you can refer to this tutorial: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

**Comment by lambert66** [comment]
Hi, thanks for sharing. I have a question about ./dataset.py, the code:
        newtrainpath, newtrainlabel = read_filepaths2('../data/SARS-Cov-2/train_split.txt')
        newtestpath, newtestlabel = read_filepaths2('../data/SARS-Cov-2/test_split.txt')
Do i need to build a .txt by myself?
The other question, i alreadt download 'COVID-CT' and 'SARS-Cov-2' datasets, should i do something else except put them into data/ directory?
Cause i am beginner of CL, if you can answer my questions , it will help me a lot.
Thanks again!

**Comment by Kyfafyd** [comment]
Hi @lambert66, thanks for your interest!
The '.txt' files have been preprocessed by us and provided in google drive link in readme, there is no need to generate these files by yourself.
Can you run the code after downloading the data?

**Comment by lambert66** [comment]
The problem has been solved, cause my dataset was downloaded incorrectly. Thanks a lot for your answer.
