### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.object_. 

### ISSUE THREAD

**Issue by lambert66** [med-air/Contrastive-COVIDNet#6]
D:\Anaconda\envs\cyb\python.exe D:/lambert/CL/Contrastive-COVIDNet-master/code/main.py
Building model, loading data...

train examples =  4034
test examples =  823

Checkpoint folder: saved/cont 

Cosine: True 		Bna: True 		Bnd: True 		Contrastive: True 

Start training...

  0%|          | 0/127 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "D:/lambert/CL/Contrastive-COVIDNet-master/code/main.py", line 106, in <module>
    main()
  File "D:/lambert/CL/Contrastive-COVIDNet-master/code/main.py", line 56, in main
    train_metrics = train(args, model, training_generator, optimizer, epoch)
  File "D:\lambert\CL\Contrastive-COVIDNet-master\code\train.py", line 79, in train
    new_label = torch.from_numpy(np.array([target[i]]))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

Process finished with exit code 1

I got some problem. And program does not run. The problem has been posted above, can you give me some help？i will be very grateful！

**Comment by Kyfafyd** [comment]
Hi, @lambert66 Thanks for your interest!
This issue is caused by different versions of `numpy`.
Have you follow the instruction in README to create the environment?

**Comment by lambert66** [comment]
Thanks for your answer, I will try to reconfigure the environment again. Does the installation package have to be the corresponding version?

**Comment by Kyfafyd** [comment]
> Thanks for your answer, I will try to reconfigure the environment again. Does the installation package have to be the corresponding version?

The provided environment is the tested one actually, so we recommend you use our provided `environment.yaml`.
